#spring:
#  application:
#    name: PRORADI
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#  jpa:
#    open-in-view: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: create
#    generate-ddl: true
#  sql:
#    init:
#      mode: always
#
## Database Properties
spring.datasource:
  url: jdbc:postgresql://localhost:5432/skautsluzba
  username: postgres
  password: mladen

#server:
#  port: 8082
#
##spring:
##  application:
##    name: korisnik-servis
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      healthcheck:
#        enabled: true
#  instance:
#    prefer-ip-address: true/

server:
  port: 8085

#spring:
#  application:
#    name: korisnik-servis

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
spring:
  application:
    name: eurekaclient
